### ISSUE TITLE
XML format changing for possible values of bitmasks

### ISSUE THREAD

**Issue by hamishwillee** [Auterion/libmav#41]
@ThomasDebrunner FYI, the format of XML for bitmasks has been changed so you can do `2**4` to indicate a particular bit setting.
This is a lot more readable on large values. So far we just updated the XSD.

https://github.com/ArduPilot/pymavlink/pull/920#top

**Comment by ThomasDebrunner** [comment]
Thanks @hamishwillee , working on this here: https://github.com/Auterion/libmav/pull/42

**Comment by ThomasDebrunner** [comment]
This has been implemented with https://github.com/Auterion/libmav/pull/42
